[package]
name = "landboard-ico-second-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.landboard-ico-second]
path = ".."

[dependencies.elrond-wasm]
version = "0.29.3"

[dependencies.elrond-wasm-debug]
version = "0.29.3"
